version: "3.9"
services:
  backend:
    build: ./kinematik-backend
    image: kinematik-backend:latest
    ports:
      - "5000:80"
    depends_on:
      - database
    environment:
      - KINEMATIK_CONNECTION_STRING=Server=database,1433; Database=Kinematik; User=sa; Password=${DB_PASSWORD:?err};

  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=1
      - SA_PASSWORD=${DB_PASSWORD:?err}
    ports:
      - "1433:1433"
    volumes:
      - ${DB_VOLUME_PATH:?err}:/var/opt/mssql/data

  client-frontend:
    build: ./kinematik-client-frontend
    image: kinematik-client-frontend:latest
    ports:
      - "5001:3000"

  admin-frontend:
    build: ./kinematik-admin-frontend
    image: kinematik-admin-frontend:latest
    ports:
      - "5002:3000"

  reverse-proxy:
    image: nginx:latest
    depends_on:
      - backend
      # - client-frontend
      # - admin-frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"